### ISSUE TITLE
Can't drop plugin on recycle bin

### ISSUE THREAD

**Issue by Knorrke** [aeneasr/editor-issues#1]
Dropping a plugin on recycle bin does not work (Firefox v42.0, Windows)
![editor-drop-error](https://cloud.githubusercontent.com/assets/11499926/16982386/bca28764-4e6f-11e6-88f9-f4d15e038415.png)

**Comment by Knorrke** [comment]
Works fine on Chrome, though.

**Comment by aeneasr** [comment]
should be solved now
